version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
  node: circleci/node@5.0.3
jobs:
  build-and-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: Run tests
      - run:
          command: npm run build
          name: Build app
workflows:
  build-and-test:
    jobs:
    - cypress/run:
        record: true
          - build-and-test